/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   anypoint-signin-styles.html
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

/// <reference path="../iron-flex-layout/iron-flex-layout-classes.d.ts" />
/// <reference path="../paper-styles/shadow.d.ts" />
/// <reference path="../anypoint-styles/colors.d.ts" />

